stages:
  train:
    cmd: python training/train.py
    deps:
    - data/cleaned.csv
    - training/train.py
    params:
    - params.yaml:
    outs:
    - models
    metrics:
    - metrics.json:
        cache: false
    plots:
    - plots:
        cache: false
