name: CI
on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zip code for deployment
      run: zip -r terraform/app/code-$COMMIT_ID.zip .

    - name: Set up Python 3.9.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.10"
    - name: Check platform
      run: python -c "import platform; print(platform.machine())"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Set up dvc
      uses: iterative/setup-dvc@v1
    - name: Check out dvc files
      run: make dvc-pull

    - name: Set up poetry
      uses: Gr1N/setup-poetry@v7
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: poetry --version

    - name: Install OS dependencies
      run: |
        sudo apt-get update && export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -y install --no-install-recommends \
          build-essential \
          libedit-dev  \
          libhdf5-dev

    - name: Install python libraries
      run: |
        poetry install
        
    - name: Run unit tests
      run: |
        make unit-tests

    - name: Install terraform
      uses: hashicorp/setup-terraform@v1

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: latest

    - name: Check Terragrunt
      run: terragrunt --version

    - name: Terragrunt apply
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        COMMIT_ID: ${{ github.sha }}
      run: make tf-apply-app